version: '2'
services:

  web:
    image: ansible/awx:15.0.1
    container_name: awx_web
    logging:
      driver: json-file
    depends_on:
      - redis
      - postgres
    ports:
      - "8081:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./environment.sh:/etc/tower/conf.d/environment.sh"
      - "./credentials.py:/etc/tower/conf.d/credentials.py"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./redis_socket:/var/run/redis/:rw"
#      - "/root/.ssh/server.pem:/etc/nginx/awxweb.pem:ro"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx:15.0.1
    container_name: awx_task
    logging:
      driver: json-file
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./environment.sh:/etc/tower/conf.d/environment.sh"
      - "./credentials.py:/etc/tower/conf.d/credentials.py"
      - "./redis_socket:/var/run/redis/:rw"
#      - "/root/.ssh/server.pem:/etc/nginx/awxweb.pem:ro"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    logging:
      driver: json-file
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "./redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:10
    container_name: awx_postgres
    logging:
      driver: json-file
    restart: unless-stopped
    volumes:
      - "./pgdocker/10/data/:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy: 
      https_proxy: 
      no_proxy: 


volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
